spring:
  application:
    name: innovation

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: stranger
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # none | update | create | create-drop | validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8099

ollama:
  base-url: http://localhost:11434
  model: mistral:7b   # <-- set model here
  temperature: 0.5
  timeout:
    connect: 5s
    read: 60s



